### ISSUE TITLE
Little11

### ISSUE THREAD

**Issue by Mikisavage** [ryannair05/Little11#59] opened 2020-04-26 19:15 UTC
Hi, beautiful tweak but i found a bug.. i can't access to safari or any type of browser.. fix that, it would be perfect :)

**Comment by ryannair05** [comment] 2020-04-26 19:42
Duplicate of #50 

Cleaning Safari through iCleaner will resolve the issue.

**Closed by ryannair05** 2020-04-26 19:42 UTC
Labels: duplicate

**Comment by Mikisavage** [comment] 2020-04-26 22:11
Ok thanks
